-- Generated by scripts/hypr2lua.
-- Source: omarchy-mork-skog-theme/hyprland.conf

local activeBorderColor = "rgb(7587a6)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
    },
  },
  group = {
    col = {
      border_active = activeBorderColor,
    },
  },
})
